### ISSUE TITLE
Cannot accept invite for reviewer

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/submissions#190]
When I try to fill in the form to accept the invitation as a reviewer, I get a blank page.

**Comment by hugocorbucci** [comment]
Turns out this is throwing an error because the preferences come as a hash instead of an array via formtastic.
So we get the following error:
```
TypeError (can't convert Symbol into Integer):
  app/controllers/accept_reviewers_controller.rb:42:in `[]='
  app/controllers/accept_reviewers_controller.rb:42:in `block (2 levels) in accept_params'
  app/controllers/accept_reviewers_controller.rb:41:in `block in accept_params'
  app/controllers/accept_reviewers_controller.rb:34:in `tap'
  app/controllers/accept_reviewers_controller.rb:34:in `accept_params'
  app/controllers/accept_reviewers_controller.rb:14:in `update'
```

**Comment by hugocorbucci** [comment]
Not sure why it doesn't show the regular error page but just a blank page.
But working on fixing the actual problem for now.
